spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

currency:
  service:
    interval: 5000
    url: http://free.currencyconverterapi.com/api/v5/convert?q=EUR_USD&compact=y